### ISSUE TITLE
multipart file uploads issue + solution

### ISSUE THREAD

**Issue by diab303** [Svish/php-cross-domain-proxy#1]
php://input doesn't work on multipart file uploads so proxying file uploads won't work.

this can be resolved by putting this into .htaccess (assuming the file is called proxy.php)

```
<Files proxy.php>
php_value  enable_post_data_reading off
</Files>
```

unfortunately this option can't be changed from inside PHP but it may be useful to note in the documentation

**Comment by Svish** [comment]
Have you tested it with this added? Does it affect anything else?

Either way, thanks for the heads up 😄

**Comment by diab303** [comment]
It seems to work fine HOWEVER there is another unrelated bug (happens both with and without enable_post_data_reading  disabled) - if the server switches to Transfer-Encoding: chunked the proxied response becomes invalid. On my end this happens when the content is rather big (like.. 100k) 
There are no errors on the server side and the response seems to be OK otherwise.

If you have any idea how to resolve this it would be much appreciated.

**Comment by diab303** [comment]
okay so removing the transfer-encoding: chunked header from the output AND disabling ob_gzhandler seems to have fixed it. this is a rather ugly hack because it completely disables server-side compression but at least it works 100%

```
// Use gz, if acceptable
// ob_start('ob_gzhandler');

// Output headers
$header = substr($out, 0, $info['header_size']);
array_map('header', explode("\r\n", $header));
header_remove('Transfer-Encoding');

// And finally the body
echo substr($out, $info['header_size']);
```

**Comment by diab303** [comment]
this seems to have fixed it for good, gzip enabled

```
// Use gz, if acceptable
ob_start('ob_gzhandler');

// Output headers
$header = substr($out, 0, $info['header_size']);
array_map('header', explode("\r\n", $header));
header_remove('Transfer-Encoding');

$content = substr($out, $info['header_size']);

// Output proper content length field to avoid chunked encoding + gzip'd content issues
header('Content-Length: '.strlen($content), true);

// Output content
echo $content;
```

**Comment by Svish** [comment]
@diab303 Finally got around to add your suggested fixes now. Could you maybe test that it still works in your scenario? If you still have that scenario around and have the time 🙂

**Comment by Svish** [comment]
Nevermind! Found a big log file and put it in a remote server, and there it was. Chunked => no response, Gzip => Garbled response. And your two tweaks seems to indeed fix it 👍🏻

Thanks!

**Comment by diab303** [comment]
@Svish I'm glad it worked. I've been using my patch in production ever since and it's been working great (file uploads, all sorts of HTTP methods etc.) so I think it is OK. I will test your version when I can. Thank you!

**Comment by Svish** [comment]
@diab303 Sweet! Hopefully I haven't broken it completely now then... 🤔 Think it should be better and more sturdy now though... but guess we'll potentially find out, hehe.
