### ISSUE TITLE
Add content-length to $ignore

### ISSUE THREAD

**Issue by lightxx** [Svish/php-cross-domain-proxy#2]
This is not really an issue but a feature request: cURL automatically sets the content-length header, so content-length should be stripped from the incoming request like all the other headers in $ignore

**Comment by lightxx** [comment]
Background: I've extended your proxy class to include certain certificate information when proxying the request. Took me a while and wireshark to figure out the reason why the information never got to the proxied host, because the content-length was the 'old', pre-certificate information content-length. So the data was actually transmitted over the wire but ignored by the web server.

**Comment by Svish** [comment]
That's a good point, and even counts as a bug I'd say.

Added the header to $ignore as you suggested. Committed and tagged v2.1.6 🙂
