### ISSUE TITLE
Response for preflight has invalid HTTP status code 400

### ISSUE THREAD

**Issue by ymdahi** [Svish/php-cross-domain-proxy#4]
I'm getting the following error on my installation.

I have the proxy script running on a separate server. I've enabled the proxy script to bypass cors for my requesting domain.

For example:

proxy server: proxy.mywebsite.com
requesting server: websiteA.com
host server: websiteB.com/some/data

When I try to use the proxy server like this on the requesting server:

`$.ajax({`
  `url: 'http://proxy.mywebsite.com/proxy.php,`
  `cache: false,`
  `headers: {`
  `'X-Proxy-URL': 'http://websiteB.com/some/data',`
  `}`
`})`

I get the following errors:

> OPTIONS http://proxy.mywebsite.com/proxy.php 400 (Bad Request)

> XMLHttpRequest cannot load http://proxy.mywebsite.com/proxy.php. Response for preflight has invalid HTTP status code 400

Any help would be appreciated.

**Comment by Svish** [comment]
@ymdahi Tested doing the request with wget/curl/etc to see if the problem is between website A and the proxy, or between the proxy and website B? Is the proxy server properly configured with cors?

**Comment by ymdahi** [comment]
@Svish sorry for the late reply - yes, the error was on my part - problem was on site A, enabled cors from site B on site A and all is working. thanks for a great script!

**Comment by Svish** [comment]
Great to hear! 😀👍🏻
