### ISSUE TITLE
Support for lowercase or normalised headers

### ISSUE THREAD

**Issue by wernerkrauss** [Svish/php-cross-domain-proxy#5]
My for some reason changes `X-Proxy-URL` to `X-Proxy-Url` which breaks proxy.php

> X-Proxy-URL header missing

Can this be more bullet proof? #3 is a partial solution, which only works for totally lowercase headers

Edit: I'm still on v1.1.1 because this project still runs on PHP5.6 and I cannot switch to PHP7 at the moment.

**Comment by Svish** [comment]
It should already be "bullet-proof" in this regard? If you look at [proxy.php#L42](https://github.com/Svish/php-cross-domain-proxy/blob/d60d9830b7/proxy.php#L43), it converts all the headers to lower case. So yeah, ... should already be solved. 🤔

Not if you're still way back on 1.1.1 though... but yeah... you can always fork and add that fix yourself if you want, as it seems you might be doing given the notification you created a fork, hehe 😃
