### ISSUE TITLE
Usage needs to include cache-control header for handling async requests

### ISSUE THREAD

**Issue by Lord-ZBest** [Svish/php-cross-domain-proxy#7]
Script worked well right out-of-the-box (unlike the other 4 that I tried prior).

Usage in the readme should include that you need to add cache control to the header:
  Cache-Control: no-cache, no-transform

When I first started using the script, it would run synchronous (even when I was blasting async requests -- they would all stall). Most searches sent me down a session-locking path before I managed to find one about cache-control.  Because my JS is requesting the same file (php proxy), it was waiting to see if it could re-use the cached copy before sending the next request.

Can cache-control be automatically added to the response header?  Would clean up the requesting code.

**Comment by Svish** [comment]
JS running on the same client? Or different ones? Cache control on server or client? Not sure i follow 🤔

Could you give a code example? Or perhaps a PR?

**Comment by Lord-ZBest** [comment]
```
	var prj = new XMLHttpRequest();
	prj.open('get', "cors_proxy.php");
	prj.setRequestHeader("X-Proxy-URL",api_url);
	prj.setRequestHeader("Content-Type","application/json");
	prj.setRequestHeader("Cache-Control","no-cache, no-transform"); // * Allow Async *
	prj.send();	
```

I'm using an XHR request in Javascript -- to an API on a different host.  I can't make the request directly because it causes a CORS error (unless I use the --disable-web-security flag in chrome).  The 3rd party API returns a 404 when it receives an OPTIONS pre-flight request.  Which is why I have to re-direct my requests through your php script.

Without the "Cache-Control" header added -- each request stalls until the previous is complete.  It's a 3-stage set of requests (Stage 1 -- get a list of things.  Stage 2 -- get the history of each item in the list.  Stage 3 -- get details about the item in the history).  The default returns 26 items and 17 details for a total of 44 requests.

When run without the .setRequestHeader("Cache-Control","no-cache, no-transform"); -- These requests are not asynchronous and take about 29 sec to finish.  When I add the cache-control header, they set up a 6-connection pipeline and finish in 5.4 sec.  Without the header -- because all 44 of the requests are to the same resource (cors_proxy.php) -- it waits to see if it can use a cached copy so they don't happen async (they sit as "stalled" according to the network waterfall).

Your Readme doesn't mention the need for a cache-control header in the Usage -- so I had to invest some time chasing down the issue.  PHP has session-locking issues so I wasted some time down that path before I found the right solution.

![cache-control](https://user-images.githubusercontent.com/59375084/71786938-b5516400-2fce-11ea-97bc-bfb398a1424c.jpg)

**Comment by Svish** [comment]
Aha, so it's something that should be added from the client then it seems. I don't think it's a good idea to always add it (if it's even possible) directly in the proxy script, because caching is _normally_ a good thing, I think? Potentially, if it's possible to add in the script, it could maybe be added as an option?

Either way, feel free to create a PR with improved documentation and/or an added option for this.
🙂👍
